<?php
$CONFIG = array (
  'instanceid' => 'ocvsi9egky6s',
  'passwordsalt' => 't2CDntgdE2aGa+Ymsztoghrorv28oX',
  'secret' => 'oBTCS1/PT8JEJgml/hPNvmOmL197dAxF43odO29ps8p/wOpA',
  'trusted_domains' => 
  array (
    0 => '192.168.20.158',
    1 => '25.21.100.141',
    2 => 'bpsnmaxencekevin.net',
  ),
  "default_language" => "fr",
  "force_language" => "fr",
  'datadirectory' => '/var/www/html/nextcloud/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '24.0.6.1',
  'overwrite.cli.url' => 'http://192.168.20.158/nextcloud/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_admin',
  'dbpassword' => 'F-n.}^Rvpc}4o^1HDiBy2=;&x6NC>n',
  'installed' => true,
  'mail_from_address' => 'noreply.bacprosn',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'noreply.bacprosn@gmail.com',
  'mail_smtppassword' => 'krcqbcezmqmxipgh',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
);
